name: Weekly Model Comparison

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  compare-models:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full model comparison
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python src/train_model.py

      - name: Save comparison results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add models/
          git commit -m "🤖 Weekly model comparison completed" || echo "No changes"
          git push